name: Build macOS
on: [push, pull_request]

jobs:

  # Editor
  editor-mac:
    name: Editor (Mac, Development x64)
    runs-on: "macos-latest"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout LFS
      run: |
        git lfs version
        git lfs pull
    - name: Build
      run: |
        ./Development/Scripts/Mac/CallBuildTool.sh -build -log -arch=x64 -platform=Mac -configuration=Development -buildtargets=FlaxEditor

  # Game
  game-mac:
    name: Game (Mac, Release x64)
    runs-on: "macos-latest"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout LFS
      run: |
        git lfs version
        git lfs pull
    - name: Build
      run: |
        ./Development/Scripts/Mac/CallBuildTool.sh -build -log -arch=x64 -platform=Mac -configuration=Release -buildtargets=FlaxGame
